---
- name: Install packages
  hosts: localhost
  gather_facts: yes
  become: yes
  tasks:
          - name: "Install packages with default package manager"
            package:
                    name: "{{ item }}" 
                    state: present
            with_items:
                    - curl
                    - wget
                    - snapd
                    - virtualbox
                    - code
                    - vim
                    - vlc
                    - anki
                    - git
                    - zsh
                    #- fonts-powerline # Necessary for oh-my-zsh; See: https://github.com/powerline/fonts
                    
          - name: "Set up the current user to use docker without sudo"
            shell: "sudo addgroup --system docker && sudo adduser $USER docker && sudo setfacl -m user:${USER}:rw /var/run/docker.sock"

          - name: "Install packages with snap"
            snap:
                    name: "{{ item }}"
                    state: present
                    classic: yes
            with_items:
                    - docker
                    - kubectl
                    # - minikube deprecated version
                    - helm
                    - discord
                    - spotify
                    - opera
                    - mailspring

          - name: "Install Zoom (with apt package manager)"
            shell: "wget https://zoom.us/client/latest/zoom_amd64.deb && sudo apt install ./zoom_amd64.deb"

          - name: "Install Ulauncher (with apt package manager)"
            shell: "wget https://github.com/Ulauncher/Ulauncher/releases/download/5.10.0/ulauncher_5.10.0_all.deb && sudo apt install ./ulauncher_5.10.0_all.deb"

          - name:
          - name: "Check if vim config is already set"
            shell: "if grep -q '\\.vim_runtime' ~/.vimrc; then echo true; else echo false; fi"
            register: isVimConfigSet # true if it is set already; false if it needs to be set
            changed_when: false
            become: no # run as current user to access the home ~ folder

          - name: "Download vim configuration from github to ~/.vim_runtime"
            git:
                    repo: "https://github.com/amix/vimrc.git"
                    clone: yes
                    update: yes 
                    depth: 1
                    dest: "~/.vim_runtime"
            become: no # Necessary so that it finds the home folder ~
            when: not isVimConfigSet.stdout|bool # this means: run if the vim config isn't set already

          - name: "Set the vim runtime (idempotent script)"
            shell: "~/.vim_runtime/install_awesome_vimrc.sh"
            become: no
            when: not isVimConfigSet.stdout|bool # this means: run if the vim config isn't set already

            #- name: "Set ZSH as default Shell (idempotent script)"
            #shell: "if [ $(echo $SHELL) != /usr/bin/zsh ]; then chsh -s $(which zsh); fi" # Set zsh as default if it isn't already
            #become: no # Necessary to set zsh for current user not for root user

          - name: "Check if Oh-My-Zsh is installed already"
            shell: "if [ -d ~/.oh-my-zsh ]; then echo true; else echo false; fi"
            register: isOhMyZshInstalled
            changed_when: false # This task doesn't change anything

          - name: "Using Oh-my-zsh script"
            # See: https://github.com/ohmyzsh/ohmyzsh
            shell: 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh) --unattended"'
            become: no
            when: not isOhMyZshInstalled.stdout|bool # Task is only executed if Oh-My-Zsh isn't installed


          - name: Creating dir ~/Downloads/powerlevel10k-fonts
            file: state=directory path="~/Downloads/powerlevel10k-fonts"
            become: no

          - name: Download fonts for powerlevel10k ZSH-Theme in the new folder
            # See: https://github.com/romkatv/powerlevel10k#manual
            get_url: url={{ item }} dest="~/Downloads/powerlevel10k-fonts"
            with_items:
                - "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf"
                - "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf"
                - "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf"
                - "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf"
            become: no

          - name: Download powerlevel10k to Oh-My-Zsh plugins folder
            git:
                repo: https://github.com/romkatv/powerlevel10k.git
                dest: ~/.oh-my-zsh/custom/themes/powerlevel10k
                clone: yes
                depth: 1
                update: yes
            become: no


          - name: Set powerlevel10k as the default theme
            lineinfile:
                path: "~/.zshrc"
                create: yes #Create it if it isn't present
                state: present
                insertafter: EOF # inseert at End of file if regex doesn't exist
                regexp: "^ZSH_THEME="
                line: 'ZSH_THEME="powerlevel10k/powerlevel10k"'
            become: no

          - name: Set aliases in ZSH
            lineinfile:
              path: "~/.oh-my-zsh/custom/aliases.zsh"
              create: yes
              state: present
              insertafter: EOF
              regexp: "'{{ item.cmd }}'$" # checks if there is a shortcut for that command
              line: "alias {{ item.alias }}='{{ item.cmd }}'"
            become: no
            with_items:
            - { alias: k, cmd: kubectl }
            - { alias: d, cmd: sudo docker }
            - { alias: repo, cmd: cd ~/repos && pwd && ls}
            - { alias: watchk, cmd: watch kubectl get all }

          - name: "INFORMATION"
            debug:
                msg: 
                - "After the script ends ZSH will be set as the standard shell."
                - "But this will only take effect after you restart your PC."
                - "If it isn't you can run: >> chsh -s /bin/zsh <<  to change it"
                - "ZSH should welcome you with the setup wizard for powerlevel10k."
                - "If that is not the case just run: >> p10k configure <<"
                - "You may install the fonts in the ~/Downloads/powerlevel10k-fonts folder manually!"
